import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { PageShell, SiteFooter, SiteHeader } from "@/components/layout";
import { AppProviders } from "@/components/providers/AppProviders";
import { ThemeScript } from "@/components/theme";
import {
  fetchNavItemsFromApi,
  resolveNavItems,
} from "@/lib/nav-categories";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const apiNav = await fetchNavItemsFromApi();
  const navItems = resolveNavItems(apiNav);

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning={true}
    >
      <body
        className="min-h-full flex flex-col bg-background text-foreground"
        suppressHydrationWarning={true}
      >
        <ThemeScript />
        <AppProviders>
          <SiteHeader navItems={navItems} />
          <PageShell>{children}</PageShell>
          <SiteFooter />
        </AppProviders>
      </body>
    </html>
  );
}
